#!/bin/sh
if [ ! -f ReverseProcessProto.class ]; then
	javac ReverseProcessProto.java
fi
if [ ! -f modifiedPb.txt ]; then
	java ReverseProcessProto modifiedPbProcessed.txt modifiedPb.txt
fi
echo `uname -s`/ComPBBiYacc get modifiedPb.txt srcAST
`uname -s`/ComPBBiYacc get modifiedPb.txt srcAST
echo `uname -s`/ComXMLBiYacc put srcProcessed.xml srcAST
`uname -s`/ComXMLBiYacc put srcProcessed.xml srcAST
if [ ! -f ReverseProcessXML.class ]; then
	javac ReverseProcessXML.java
fi
if [ ! -f src.xml ]; then
	java ReverseProcessXML srcProcessed.xml src.xml
fi
cp openssl/src.xml .
echo fast src.xml src.c
fast src.xml src.c
echo diff src.c patched.c
diff src.c patched.c
